In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [1]:
pip install fasttext --no-cache-dir

Collecting fasttext
  Downloading fasttext-0.9.2.tar.gz (68 kB)
     ---------------------------------------- 0.0/68.8 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/68.8 kB ? eta -:--:--
     ---------------------- --------------- 41.0/68.8 kB 487.6 kB/s eta 0:00:01
     --------------------------------- ---- 61.4/68.8 kB 544.7 kB/s eta 0:00:01
     -------------------------------------- 68.8/68.8 kB 468.9 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pybind11>=2.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (2.12.0)
Requirement already satisfied: setuptools>=0.7.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (68.0.0)
Requirement already satisfied: numpy in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (1.26.2)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py): started
  Building wheel for fasttext (setup.py): finished with status 'done'
  Created wheel for fasttext: filename=fasttext-0.9.2-cp39-cp39-win_amd64.whl size=234274 sha256=aaf18072e266153a7859131012ba2ba3d1d9e968cf08f641810cbc0e57c75d0c
  Stored in directory: C:\Users\shahe\AppData\Local\Temp\pip-ephem-wheel-cache-vbx4wi_4\wheels\64\57\bc\1741406019061d5664914b070bd3e71f6244648732bc96109e
Successfully built fasttext
Installing collected packages: fasttext
Successfully installed fasttext-0.9.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
!pip install fasttext

Requirement already satisfied: fasttext in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (0.9.2)
Requirement already satisfied: pybind11>=2.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (2.12.0)
Requirement already satisfied: setuptools>=0.7.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (68.0.0)
Requirement already satisfied: numpy in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (1.26.2)

In [18]:
import pandas as pd
import numpy as np
import json
import fasttext
import re, os, shutil, json
from os import path
from numpy.linalg import norm
import pickle

# Stop Words Processing - for data cleaning
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
sw = set(stopwords.words('english'))
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shahe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shahe\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [19]:
#drive.mount('/content/gdrive')

defaultPath = "C:\\Users\\shahe\\FYP-PROJECT\\project\\FYP-1\\FYP\\"
Dataset_Folder = defaultPath + "Dataset\\"
Processed_Dataset_Pickle_Path = Dataset_Folder + "processed_dataset.pkl"
Relevant_Comments_List_Pickle_Path = Dataset_Folder + "relevant_comments_list.pkl"
FastTextModelPath = defaultPath + "FastTextModelFile\\cc_en_300-001.bin"

Reading Dataset Files and Merging them

In [20]:
Dataset_Files = os.listdir(Dataset_Folder)

In [21]:
DFs = []
length = 0

for file in Dataset_Files:
  if file.endswith('.csv'):
    df = pd.read_csv(Dataset_Folder + file, usecols=["author", "like_count", "text"])
    DFs.append(df)
    length = length + 1

In [22]:
# Merging DataFrames

dataset_df = pd.concat(DFs)
dataset_df.shape

(1044, 3)

In [23]:
dataset_df.head(5)

,author,like_count,text
0,Adan Phu,0,I actually feel better after going vegan... on...
1,K. Roberts,1,Any time I’ve tried going vegan i overeat beca...
2,Sarar Shleweet,0,"Did not lose weight, did not feel tired, no la..."
3,NIA Mac,0,Feeling tired when you go vegan ??? <br><br>T...
4,Vishal Singh,0,Well I&#39;m a Hindu and non-veg food aren&#39...

In [24]:
ls

 Volume in drive C is Windows
 Volume Serial Number is BA06-CAE6

 Directory of C:\Users\shahe\FYP-PROJECT\project\FYP-1\FYP

05/12/2024  03:18 PM    <DIR>          .
05/11/2024  02:45 AM    <DIR>          ..
05/11/2024  02:52 AM    <DIR>          .ipynb_checkpoints
05/11/2024  02:41 AM     7,237,176,312 cc_en_300-001-001.bin
05/11/2024  02:44 AM    <DIR>          Dataset
05/11/2024  02:44 AM           137,152 Extract_Relevant_Comments and Summarize.ipynb
05/12/2024  03:18 PM           174,632 Extract_Relevant_Comments_and_Summarize (1)-Copy1.ipynb
05/11/2024  01:52 PM    <DIR>          FastTextModelFile
05/11/2024  02:44 AM             7,771 filtering_data.ipynb
05/11/2024  02:44 AM            54,901 Fine_Tuning_Code.ipynb
05/11/2024  02:44 AM            47,839 Fine_Tuning_Code-Check.ipynb
05/11/2024  02:44 AM            16,811 FYP_SUMMARIZATION_MODEL_USE_CASE.ipynb
05/11/2024  02:44 AM            31,368 LOADING DATA AND GENERATING SUMMARY.ipynb
05/12/2024  11:57 AM               272 login.html
05/12/2024  11:53 AM    <DIR>          template
05/12/2024  12:03 PM    <DIR>          templates
               9 File(s)  7,237,647,058 bytes
               7 Dir(s)  100,243,763,200 bytes free

Dataset Preprocessing

In [25]:
# Defining Text Preprocing Function

def remove_stop_words(text):
  text_tokens = word_tokenize(text)
  tokens_without_sw = [word for word in text_tokens if not word in sw]
  return ' '.join(map(str, tokens_without_sw))


def preprocess(text):

    text = text.lower()
    text = text.replace("\\n", " ").replace("\n", " ")      # remove \n
    text = remove_stop_words(text)                          # remove stop words
    text = re.sub(r'\b\w{1,2}\b', ' ', text)                # remove words with 1 or 2 characters only
    text = re.sub(r'[^ a-zA-Z0-9]+','', text)                  # remove special characters / remove all except characters and spaces

    if text == "nan" or text == "none":
        text = " "
    text = re.sub(' +', ' ', text)

    return text.strip()

FastText - Features Generation

In [26]:
import fasttext
fastText_model = fasttext.load_model('cc_en_300-001-001.bin')

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [27]:
def fasttext_EmbeddingsGenerator(text):
  text_embeddings = fastText_model.get_word_vector(text)
  return text_embeddings

Sentence Transformer - Features Generation

TF-IDF - Features Generation

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

#print("no. of docs, no. of unique corpus words) : ", tfidf_features_array.shape)
#returns two dimensional feature array against the entire corpus(dataset).
def TFIDF_EmbeddingsGenerator(corpus):
  tfidf_model = TfidfVectorizer(stop_words='english')
  tfidf_model = tfidf_model.fit(corpus) #provide dataset.
  tfidf_features = tfidf_model.transform(corpus) #returns features.
  tfidf_features_array = tfidf_features.toarray() #converts to array.
  tfidf_features_list = []
  for arr in tfidf_features_array:
    tfidf_features_list.append(arr) #appending feature arrays into a list.
  return (tfidf_features_list, tfidf_model)

#generating feature array against the query.
#This function Takes in dataset's feature array and the query.
def TFIDF_QueryFeatureGeneration(tfidf_model, query):
  tfidf_features = tfidf_model.transform([query])
  tfidf_features_array = tfidf_features.toarray()
  return tfidf_features_array[0]

**Creating feature vectors of our Dataset**

In [29]:
# Looping over dataset to generate feature vectors
processed_text = []
fasttext_features = []
tfidf_features = []

for index, row in dataset_df.iterrows():

  processed = preprocess(row["text"]) #sending data for cleaning.
  processed_text.append(processed) #appending in the list.

  # FastText Features Generator
  text_features = fasttext_EmbeddingsGenerator(processed) #takes in one comment at a time and returns features.
  fasttext_features.append(text_features)

  #Sentence Transformer Features Generator
  #
  #

# TFIDF Features Generator
(tfidf_features, tfidf_model) = TFIDF_EmbeddingsGenerator(processed_text) #passing the corpus. The func returns the trained model and extracted features.

dataset_df["processed_text"] = processed_text
dataset_df["fasttext_features"] = fasttext_features
dataset_df["tfidf_features"] = tfidf_features

dataset_df.to_pickle(Processed_Dataset_Pickle_Path, compression='infer', protocol=5, storage_options=None) #saving features data into pickle file.

**Reading Processed Dataset**

In [30]:
dataset_df = pd.read_pickle(Processed_Dataset_Pickle_Path) #reading the file.
dataset_df.head(5)

,author,like_count,text,processed_text,fasttext_features,tfidf_features
0,Adan Phu,0,I actually feel better after going vegan... on...,actually feel better going vegan one drink kac...,"[0.002285124, -0.011500623, -0.0016644135, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,K. Roberts,1,Any time I’ve tried going vegan i overeat beca...,time tried going vegan overeat foods feel sati...,"[0.0012658992, -0.007067469, -0.0031459576, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,Sarar Shleweet,0,"Did not lose weight, did not feel tired, no la...",lose weight feel tired lack vitamin b12 felt i...,"[0.0028238988, -0.005313926, 0.005609359, 0.01...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,NIA Mac,0,Feeling tired when you go vegan ??? <br><br>T...,feeling tired vegan time feel tired get enough...,"[0.0029572814, -0.0057881805, -0.009282095, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,Vishal Singh,0,Well I&#39;m a Hindu and non-veg food aren&#39...,well hindu nonveg food allowed religion sin ea...,"[0.0013959595, -0.0027295456, -0.0015057367, 0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [31]:
print("fasttext", type(dataset_df["fasttext_features"]))
print("tfidf   ", type(dataset_df["tfidf_features"]))

fasttext <class 'pandas.core.series.Series'>
tfidf    <class 'pandas.core.series.Series'>

**Defining function to extract relevant comments w.r.t query**

In [32]:
def cosine_similarity(A, B):

  # compute cosine similarity to find the similarity between two vectors.Higher the value, higher the similarity.
  cosine = np.dot(A,B)/(norm(A)*norm(B))
  return cosine
def get_relevant_comments_indices(query, comments, top_relevant_comments):
  #finding out relevant comments by returning indexes.
#comments: list of feature vectors.
  cosine_similarities = {}
  index = 0

  for comment in comments:
    cosine = cosine_similarity(query, comment) #calculating cosine similarity between query and the feature vector in feature vector list.
    cosine_similarities[cosine] = index #making a dictionary - key-value pair, cosine is the key and index is value.
    index = index + 1

  # Sort by key
  sorted_cosine_similarities = dict(sorted(cosine_similarities.items(), reverse = True)) #returning a dict of sorted keys(highest cosine value).
  print(sorted_cosine_similarities)
  # create a list of of relevant comments indices
  relevant_indices = []
  for i in range(0, top_relevant_comments): #top_relevant_comments= count.
    key, value = list(sorted_cosine_similarities.items())[i] #accessing top values to get the index of the comment.
    relevant_indices.append(value)

  return relevant_indices

**Ask user query and find relevant comments**

In [33]:
query = input()

# query text preprocessing
processed_query = preprocess(query)

# FastText Features Generator
query_FastText_features = fasttext_EmbeddingsGenerator(processed_query)
# TFIDF Features Generator
query_TFIDF_features = TFIDF_QueryFeatureGeneration(tfidf_model, processed_query)


indices = get_relevant_comments_indices(query_TFIDF_features, dataset_df["tfidf_features"].tolist(), 10) #giving feature vectors of query and the dataset.

print(type(query_TFIDF_features), type(dataset_df["tfidf_features"].tolist()))
print(type(query_TFIDF_features[0]), type(dataset_df["tfidf_features"].tolist()[0]))

# I want to adopt keto diet

 I want to adopt keto

{0.28028433498079: 626, 0.2089522075459834: 264, 0.19922243510089668: 846, 0.18646717677144667: 131, 0.1842336803672835: 968, 0.173471732526749: 606, 0.16400262658266637: 605, 0.1606648798751931: 871, 0.15041898600510326: 976, 0.14628949964161514: 804, 0.14338225311398708: 602, 0.1405938652111038: 380, 0.13770991129163251: 651, 0.13645562765834554: 124, 0.13297799888665718: 789, 0.13028214573723804: 603, 0.13008533356364846: 29, 0.1295484402623706: 916, 0.1282357025326921: 127, 0.11716459303143181: 531, 0.11636686827034678: 79, 0.113757535275481: 38, 0.11356034161988991: 695, 0.11171465540250672: 877, 0.1112494042673343: 625, 0.11025604828634389: 966, 0.10830677118040288: 1027, 0.10827498625737972: 742, 0.10770497236839166: 848, 0.10730366822619139: 957, 0.10682538286793183: 649, 0.10661690928858333: 176, 0.10617872141600135: 220, 0.10558643943115129: 755, 0.10330752023901607: 831, 0.10277928971168203: 835, 0.10210697037042264: 987, 0.10131652598353307: 5, 0.09384843407037836: 878, 0.0935713037330124: 212, 0.09253343405265269: 937, 0.092159971395097: 739, 0.09210132751577951: 203, 0.0906611930997805: 913, 0.08997876402043582: 604, 0.08911533173117808: 632, 0.08896334998389568: 645, 0.08754082989569185: 708, 0.08750508985291969: 784, 0.08567542177418361: 716, 0.08408344194904564: 991, 0.08353004197203653: 318, 0.08254870368471771: 845, 0.08226068424842899: 782, 0.08111635980064112: 722, 0.08108767059238167: 806, 0.07996473677768445: 853, 0.07937655185316872: 1029, 0.07933475676138406: 772, 0.07883508150054207: 981, 0.07784723588261307: 620, 0.077737863448585: 761, 0.07734370812590127: 274, 0.07672778285232291: 1023, 0.07639639670805852: 261, 0.07636144748922576: 310, 0.07582757717650064: 597, 0.0744745505404107: 965, 0.07396286195100725: 962, 0.07313081180555268: 596, 0.07243560057928033: 950, 0.07146585578427979: 616, 0.07057139939746837: 1025, 0.06999400319884086: 778, 0.06970366880304622: 926, 0.06919822981144101: 711, 0.06913294255106256: 672, 0.06912252656742941: 898, 0.06876226703801186: 234, 0.06705786505633067: 918, 0.06623209213079885: 1024, 0.06601988342935249: 894, 0.06544992645231949: 1010, 0.06509015948684974: 967, 0.06503104368578504: 974, 0.06477433336016436: 600, 0.06420607597087805: 820, 0.06419012869351291: 954, 0.06264672199467587: 927, 0.06203782882584397: 546, 0.061671197301698615: 172, 0.06111291975230156: 1003, 0.0609201273605623: 1042, 0.06043710089318982: 859, 0.06037018361368988: 769, 0.05920206448403367: 643, 0.059163793681913414: 880, 0.05914893081317747: 520, 0.05884250974121999: 1035, 0.05858770770346882: 757, 0.05837760467440459: 923, 0.058166739480141644: 1008, 0.058075835462160996: 791, 0.05786730625970782: 78, 0.05777542962346816: 500, 0.05774321883423347: 247, 0.056533519285958234: 572, 0.05653034196108545: 407, 0.056370022957694374: 865, 0.05585578423238966: 986, 0.05538065822241275: 694, 0.05526472974101262: 629, 0.05519457719585602: 857, 0.05494229927733919: 858, 0.05459801767431846: 1009, 0.05378971570763544: 826, 0.05330963618829812: 815, 0.0532054894030018: 995, 0.05288137768966292: 908, 0.05272095951599122: 644, 0.05237349322548042: 115, 0.052297329684490704: 943, 0.05222581524410631: 637, 0.051937903694993126: 790, 0.051737232333108: 897, 0.05088388983001623: 803, 0.05064372362079142: 194, 0.050575506431891994: 627, 0.05036087853111091: 642, 0.04992479328332943: 984, 0.04978051242887536: 844, 0.0496374562271257: 958, 0.049545520454272296: 932, 0.04902233241583645: 122, 0.04889299410047371: 241, 0.04857095752660155: 942, 0.047988183132432534: 1039, 0.04797405959441485: 771, 0.04775291250493062: 861, 0.047615036713049105: 418, 0.04734025584656857: 578, 0.04733797120680457: 774, 0.047078245272314585: 752, 0.04684561857917379: 685, 0.04684560019263518: 1018, 0.046475377223697455: 618, 0.046471365656903414: 639, 0.04638242163084555: 703, 0.04621742957924737: 971, 0.04587278789971572: 867, 0.045798336783016355: 687, 0.04512309381224472: 843, 0.04426735542611546: 988, 0.04418855392227946: 278, 0.04417820031268828: 854, 0.043926701331805665: 650, 0.043767906428773234: 852, 0.04364402033401615: 759, 0.043394767645940815: 748, 0.04321612165348881: 675, 0.04321511183090454: 947, 0.04319102864508891: 902, 0.042069259293548183: 641, 0.042014309299437995: 617, 0.04163827292790143: 288, 0.041367085341791246: 837, 0.04125101704572844: 594, 0.041169180588045994: 760, 0.04114830042101258: 529, 0.04113365327663052: 608, 0.041042028983689215: 240, 0.04093665780718453: 646, 0.04079158906892895: 921, 0.040667071135473194: 279, 0.04027256204178898: 832, 0.04022211549633927: 647, 0.040094121915588816: 640, 0.04001026627460485: 186, 0.03989671997482423: 928, 0.03974236523853578: 833, 0.03961523321992536: 373, 0.03960277884794771: 152, 0.0395798684005182: 840, 0.03941670458552841: 1032, 0.03895260626936383: 648, 0.03831409314335292: 445, 0.038147324591146205: 952, 0.03791643559311055: 354, 0.037906568876625184: 1007, 0.0377438899241561: 941, 0.03746724508747604: 314, 0.03736412086513134: 459, 0.03714417985271398: 889, 0.03703676363761608: 381, 0.03702538320808081: 830, 0.03667702397762856: 451, 0.03637257426119102: 810, 0.036337033654733585: 334, 0.03621264300563219: 333, 0.036051435070146895: 698, 0.03565670172187803: 948, 0.03542141091982075: 433, 0.035299554346434094: 395, 0.035267663667832516: 26, 0.034776088855240014: 1030, 0.034563083556235004: 33, 0.03448102582613918: 960, 0.03379717358210166: 486, 0.03371113512413631: 466, 0.033709292215301175: 660, 0.03367162717197658: 881, 0.03364067221880627: 95, 0.033616348090836794: 992, 0.03359623891180207: 514, 0.033373292065707334: 411, 0.033329010703133245: 290, 0.033133861762537825: 768, 0.03293359202213762: 235, 0.0327082838487951: 872, 0.032504210316698284: 899, 0.031608762944241746: 634, 0.031197928392873338: 1012, 0.030751165522122464: 744, 0.030470614636821845: 696, 0.030256697344982455: 745, 0.03010896394150168: 935, 0.030086649045426864: 93, 0.029375900286969205: 630, 0.029239903698769897: 863, 0.029173555787021507: 623, 0.029141113839830216: 886, 0.028933715851226813: 939, 0.02889071985245504: 951, 0.02804857990712945: 589, 0.02762332534440031: 285, 0.027531817499051224: 287, 0.027371574606349078: 558, 0.027370465020817678: 633, 0.027238640278623934: 249, 0.02710094167850228: 842, 0.02640492773138928: 64, 0.02603155931425551: 358, 0.025974861997141174: 834, 0.025950401464680226: 775, 0.025690751025507753: 793, 0.025400317799574624: 375, 0.025123073857931583: 441, 0.024935630429832562: 816, 0.024554051524016213: 993, 0.024324783453837175: 263, 0.024146174678802475: 912, 0.023807835723033237: 825, 0.023618851821210284: 818, 0.023556838287421823: 839, 0.023520389083205986: 796, 0.023318662906735864: 910, 0.022827050488533535: 873, 0.02251827385451629: 1013, 0.021684545748941356: 414, 0.021260631409142226: 478, 0.021156658387403757: 517, 0.02110451137128404: 245, 0.020646443135857225: 85, 0.02053896028927906: 355, 0.020207388149533254: 1002, 0.02011869187964702: 977, 0.020092340888851812: 113, 0.019765038844684907: 50, 0.01934389950842785: 479, 0.01921897850528485: 624, 0.01870856928317254: 422, 0.018501298862537305: 914, 0.018210387024134352: 440, 0.017782094278546077: 32, 0.017522226684210565: 526, 0.01727092250696218: 4, 0.016639233617652245: 485, 0.01661786865014115: 994, 0.016423814384627238: 232, 0.01609604090273914: 541, 0.015526664429223253: 673, 0.01519375280630262: 499, 0.014799737562145442: 246, 0.01173567694022651: 504, 0.006266808726669383: 458, 0.0: 1043}
<class 'numpy.ndarray'> <class 'list'>
<class 'numpy.float64'> <class 'numpy.ndarray'>

In [25]:
indices

[626, 264, 846, 131, 968, 606, 605, 871, 976, 804]

In [35]:
relevancy_count = 1
relevant_comments_list = []
Comments_str = ""

print("Most Relevant Comments w.r.t Query\n")
for index in indices:
  comment = dataset_df.iloc[index]["text"]
  print(str(relevancy_count) + " relevant comment: " + comment)
  relevancy_count = relevancy_count + 1
  relevant_comments_list.append(comment)
  Comments_str = Comments_str + comment + ". "


with open(Relevant_Comments_List_Pickle_Path, 'wb') as f:
  pickle.dump(relevant_comments_list, f)

Most Relevant Comments w.r.t Query

1 relevant comment: But I don&#39;t want to lose weight
2 relevant comment: What can I do to gain weight? I don’t want to eat garbage but I also want to gain weight
3 relevant comment: I tried KETO ,  83 TO 68
4 relevant comment: What if i dont want too loose weight?
5 relevant comment: sir i am very confused plz help i am 5 &#39;3.5&quot; and weight is 60 i want to increase height and also want muscles
6 relevant comment: Just wondering after the keto out, I&#39;ve learnt that I&#39;d better do the 7 day plan to come back to my normal diet in this video. So can I eat whatever I want to eat and exercise to keep the weight after the 7 day plan that you suggested? Would that maintain my weight? I really can&#39;t follow keto diet forever.. I&#39;d rather eat something I want and exercise to keep my weight.. is that a bad idea? I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever.. Could someone reply my questions above please?
7 relevant comment: I want to start with keto diet and I&#39;m a girl and I weigh around 84 KGS please tell me after completing 40 days of keto how much weight I can loose? also let me know wether having boiled eggs with some masala can be eaten In keto diet?
8 relevant comment: Hello sir , I want to know can a nursing mother go for keto diet to reduce weight
9 relevant comment: after keto diet <br>what should I do for not gain weight
10 relevant comment: Love this! I don&#39;t normally leave comments but I feel like Keto has saved my life. I was overweight for years and no diet or exercise was working. I almost gave up but then I heard about keto so gave it a shot. I lost over 20lbs in the first month. It wasn&#39;t easy though! There&#39;s something called the keto flu that really threw me out of wack until I started taking a supplement to fight it off. If you are doing keto or thinking about starting keto I suggest this supplement to help you fight off the keto flu and help you stay in ketosis (<a href="https://bit.ly/2RYsl94)">https://bit.ly/2RYsl94)</a> I&#39;ve lost over 48lbs on keto so far and I&#39;m 22lbs away from my goal. Keto saved me when nothing else worked. I will be forever thankful to keto lol.

In [36]:
print(relevant_comments_list)

['But I don&#39;t want to lose weight', 'What can I do to gain weight? I don’t want to eat garbage but I also want to gain weight', 'I tried KETO ,  83 TO 68', 'What if i dont want too loose weight?', 'sir i am very confused plz help i am 5 &#39;3.5&quot; and weight is 60 i want to increase height and also want muscles', 'Just wondering after the keto out, I&#39;ve learnt that I&#39;d better do the 7 day plan to come back to my normal diet in this video. So can I eat whatever I want to eat and exercise to keep the weight after the 7 day plan that you suggested? Would that maintain my weight? I really can&#39;t follow keto diet forever.. I&#39;d rather eat something I want and exercise to keep my weight.. is that a bad idea? I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever.. Could someone reply my questions above please?', 'I want to start with keto diet and I&#39;m a girl and I weigh around 84 KGS please tell me after completing 40 days of keto how much weight I can loose? also let me know wether having boiled eggs with some masala can be eaten In keto diet?', 'Hello sir , I want to know can a nursing mother go for keto diet to reduce weight', 'after keto diet <br>what should I do for not gain weight', 'Love this! I don&#39;t normally leave comments but I feel like Keto has saved my life. I was overweight for years and no diet or exercise was working. I almost gave up but then I heard about keto so gave it a shot. I lost over 20lbs in the first month. It wasn&#39;t easy though! There&#39;s something called the keto flu that really threw me out of wack until I started taking a supplement to fight it off. If you are doing keto or thinking about starting keto I suggest this supplement to help you fight off the keto flu and help you stay in ketosis (<a href="https://bit.ly/2RYsl94)">https://bit.ly/2RYsl94)</a> I&#39;ve lost over 48lbs on keto so far and I&#39;m 22lbs away from my goal. Keto saved me when nothing else worked. I will be forever thankful to keto lol.']

**Text Sumarization**

In [37]:
!pip install evaluate

Requirement already satisfied: evaluate in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (0.4.0)
Requirement already satisfied: datasets>=2.0.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (2.11.0)
Requirement already satisfied: numpy>=1.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (1.26.2)
Requirement already satisfied: dill in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.3.6)
Requirement already satisfied: pandas in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (2.1.4)
Requirement already satisfied: requests>=2.19.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (4.65.0)
Requirement already satisfied: xxhash in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.70.14)
Requirement already satisfied: fsspec>=2021.05.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2023.10.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.19.4)
Requirement already satisfied: packaging in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (23.1)
Requirement already satisfied: responses<0.19 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets>=2.0.0->evaluate) (14.0.1)
Requirement already satisfied: aiohttp in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets>=2.0.0->evaluate) (3.9.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: filelock in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (2023.11.17)
Requirement already satisfied: colorama in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->evaluate) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->evaluate) (2023.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)

In [38]:
import nltk
import numpy as np
import pickle
from datasets import load_dataset
from transformers import T5Tokenizer, DataCollatorForSeq2Seq
from transformers import T5ForConditionalGeneration, Seq2SeqTrainingArguments, Seq2SeqTrainer

from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from transformers import GenerationConfig

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

defaultPath = "/content/gdrive/MyDrive/FYP-1/FYP1/"
Dataset_Folder = defaultPath + "Dataset/"
Processed_Dataset_Pickle_Path = Dataset_Folder + "processed_dataset.pkl"
Relevant_Comments_List_Pickle_Path = Dataset_Folder + "relevant_comments_list.pkl"
FastTextModelPath = defaultPath + "FastTextModelFile/cc.en.300-001.bin"

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

**Read relevant_comments_list**

In [39]:
relevant_comments_list = []

with open(Relevant_Comments_List_Pickle_Path, 'rb') as f:
  relevant_comments_list = pickle.load(f)

#relevant_comments_str = relevant_comments_list[0]
relevant_comments_str = ". ".join(relevant_comments_list) #merging all comments into a single string.

In [40]:
#model_name='facebook/bart-large-cnn'
# model_name = "SyedShaheer/ignore_mode"
model_name='SyedShaheer/distilbart-cnn-12-6_TUNED'
#model_name='SyedShaheer/my_awesome_billsum_model'
#model_name = 'SyedShaheer/SUMMARIZING_STRESSED_MODEL'
# model_name = 'SyedShaheer/pegasus-xsum_tuned'
#model_name = 'SyedShaheer/bart-large-cnn-samsum_tuned'
#model_name = 'SyedShaheer/SUMMARIZING_STRESSED_MODEL'
#model_name = "SyedShaheer/my_awesome_billsum_model2"
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

In [41]:
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

In [42]:
dialogue = relevant_comments_str

prompt = f"""
Comment:

{dialogue}

Generate a summary?
"""

#generation_config = GenerationConfig(max_new_tokens=10, do_sample=True, temperature=0.5)

inputs = tokenizer(prompt, return_tensors='pt')


output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        max_new_tokens=100,
        #generation_config=generation_config,
        )[0],
    skip_special_tokens=True
)

print("-----\n")
print(f'INPUT PROMPT:\n{prompt}')

print("-----\n")
print(f'MODEL GENERATION - \n{output}\n')

-----

INPUT PROMPT:

Comment:

But I don&#39;t want to lose weight. What can I do to gain weight? I don’t want to eat garbage but I also want to gain weight. I tried KETO ,  83 TO 68. What if i dont want too loose weight?. sir i am very confused plz help i am 5 &#39;3.5&quot; and weight is 60 i want to increase height and also want muscles. Just wondering after the keto out, I&#39;ve learnt that I&#39;d better do the 7 day plan to come back to my normal diet in this video. So can I eat whatever I want to eat and exercise to keep the weight after the 7 day plan that you suggested? Would that maintain my weight? I really can&#39;t follow keto diet forever.. I&#39;d rather eat something I want and exercise to keep my weight.. is that a bad idea? I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever.. Could someone reply my questions above please?. I want to start with keto diet and I&#39;m a girl and I weigh around 84 KGS please tell me after completing 40 days of keto how much weight I can loose? also let me know wether having boiled eggs with some masala can be eaten In keto diet?. Hello sir , I want to know can a nursing mother go for keto diet to reduce weight. after keto diet <br>what should I do for not gain weight. Love this! I don&#39;t normally leave comments but I feel like Keto has saved my life. I was overweight for years and no diet or exercise was working. I almost gave up but then I heard about keto so gave it a shot. I lost over 20lbs in the first month. It wasn&#39;t easy though! There&#39;s something called the keto flu that really threw me out of wack until I started taking a supplement to fight it off. If you are doing keto or thinking about starting keto I suggest this supplement to help you fight off the keto flu and help you stay in ketosis (<a href="https://bit.ly/2RYsl94)">https://bit.ly/2RYsl94)</a> I&#39;ve lost over 48lbs on keto so far and I&#39;m 22lbs away from my goal. Keto saved me when nothing else worked. I will be forever thankful to keto lol.

Generate a summary?

-----

MODEL GENERATION -
 Keto diet has helped me lose 48lbs and I'm 22lbs away from my goal. It is good to lose weight but it is hard to do it forever. I am confused whether to keep on doing keto or not. Keto saved me when nothing else worked. I recommend a supplement to help fight off the keto flu and help you stay in ketosis.

In [34]:
pip install flask

Requirement already satisfied: flask in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: Werkzeug>=2.2.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from flask) (2.2.3)
Requirement already satisfied: Jinja2>=3.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from flask) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from flask) (2.0.1)
Requirement already satisfied: click>=8.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from flask) (8.1.7)
Requirement already satisfied: importlib-metadata>=3.6.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from flask) (6.0.0)
Requirement already satisfied: colorama in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from click>=8.0->flask) (0.4.6)
Requirement already satisfied: zipp>=0.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from importlib-metadata>=3.6.0->flask) (3.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from Jinja2>=3.0->flask) (2.1.1)

In [36]:
hello = "hello world"

In [48]:
from flask import Flask
app = Flask(__name__)

@app.route('/hello/<name>')
def hello_name(name):
    return 'hello %s' % name

if __name__ == '__main__':
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [11/May/2024 14:17:26] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [11/May/2024 14:17:30] "GET /hello/shaheer HTTP/1.1" 200 -

In [62]:
from flask import Flask, redirect, url_for, request
app = Flask(__name__)

@app.route('/success/<name>')
def success(name):
    return 'Hello %s!' % name
 
@app.route('/login', methods=['POST','GET'])
def login():
    if request.method == 'POST':
        user = request.form['nm']
        return redirect(url_for('success', name = user))
    else:
        user = request.args.get('nm')
        return redirect(url_for('success', name=user))
        
if __name__ == '__main__':
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [11/May/2024 21:50:13] "GET / HTTP/1.1" 404 -
[2024-05-11 21:50:17,715] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\shahe\AppData\Local\Temp\ipykernel_10788\1536053298.py", line 15, in login
    return redirect(url_for('success', name=user))
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\helpers.py", line 256, in url_for
    return current_app.url_for(
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'success'. Did you forget to specify values ['name']?
127.0.0.1 - - [11/May/2024 21:50:17] "GET /login HTTP/1.1" 500 -
127.0.0.1 - - [11/May/2024 21:51:02] "GET /login:10 HTTP/1.1" 404 -
127.0.0.1 - - [11/May/2024 21:52:29] "GET /login?nm=123 HTTP/1.1" 302 -
127.0.0.1 - - [11/May/2024 21:52:29] "GET /success/123 HTTP/1.1" 200 -

In [14]:
from flask import Flask, redirect, url_for, request
app = Flask(__name__)
 
 
@app.route('/success/<name>')
def success(name):
    return 'welcome %s' % name
 
 
@app.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        user = request.form['nm']
        return redirect(url_for('success', name=user))
    else:
        user = request.args.get('nm')
        return redirect(url_for('success', name=user))


if __name__ == '__main__':
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/May/2024 11:56:00] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:00] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:00] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:00] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:00] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:01] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:01] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:01] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:01] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:01] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:01] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:01] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:02] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:03] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:04] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:05] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:06] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:07] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:07] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:08] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:08] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:08] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:08] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:09] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:09] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:09] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:09] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:09] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:09] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:10] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:10] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:10] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:10] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:56:10] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:29] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:29] "GET /login?name=123 HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:29] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:30] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:30] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:30] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:30] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:30] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:30] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:31] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:31] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:31] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:31] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:31] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:31] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:32] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:32] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:32] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:32] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:32] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:33] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:34] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:34] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:34] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:34] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:34] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:35] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [12/May/2024 11:57:35] "GET /login HTTP/1.1" 302 -

In [13]:
from werkzeug.wrappers import Request, Response
import numpy as np
from flask import Flask, request, render_template
import pickle

app = Flask(__name__, template_folder = 'template')

@app.route('/')
def index():
    return render_template('index')


@app.route('/getprediction',methods=['POST'])
def getprediction():    

    input = request.form.values()
    prediction = input

    return render_template('index.html', output='Predicted Weight in KGs :{}'.format(prediction))
   


if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2024-05-12 11:53:55,592] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\shahe\AppData\Local\Temp\ipykernel_30940\3726309148.py", line 10, in index
    return render_template('index')
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index
127.0.0.1 - - [12/May/2024 11:53:55] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [12/May/2024 11:54:01] "GET /getprediction/123 HTTP/1.1" 404 -

In [15]:
import numpy as np
from flask import Flask, request

app = Flask(__name__)

@app.route('/')
def index():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Prediction Page</title>
    </head>
    <body>
        <h1>Enter Input Values</h1>
        <form action="/getprediction" method="post">
            <label for="input_value">Input Value:</label>
            <input type="text" id="input_value" name="input_value"><br><br>
            <input type="submit" value="Submit">
        </form>
    </body>
    </html>
    """

@app.route('/getprediction',methods=['POST'])
def getprediction():    
    input_value = request.form.get('input_value')
    # Perform prediction using input_value here
    prediction = input_value  # Dummy prediction, replace with actual prediction
    
    return 'Predicted Weight in KGs: {}'.format(prediction)

if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/May/2024 12:00:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2024 12:00:21] "POST /getprediction HTTP/1.1" 200 -

In [17]:
import numpy as np
from flask import Flask, request, render_template

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        input_value = request.form.get('input_value')
        # Perform prediction using input_value here
        prediction = input_value  # Dummy prediction, replace with actual prediction
        return render_template('index.html', prediction=prediction)
    return render_template('index.html', prediction=None)

if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/May/2024 12:03:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2024 12:03:42] "POST / HTTP/1.1" 200 -

In [ ]:
import numpy as np
from flask import Flask, request, render_template

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        input_value = request.form.get('input_value')

        # ----------------------------------------------------
        query = input_value

        # query text preprocessing
        processed_query = preprocess(query)

        # FastText Features Generator
        query_FastText_features = fasttext_EmbeddingsGenerator(processed_query)
        # TFIDF Features Generator
        query_TFIDF_features = TFIDF_QueryFeatureGeneration(tfidf_model, processed_query)
        
        
        indices = get_relevant_comments_indices(query_TFIDF_features, dataset_df["tfidf_features"].tolist(), 10) #giving feature vectors of query and the dataset.
        
        print(type(query_TFIDF_features), type(dataset_df["tfidf_features"].tolist()))
        print(type(query_TFIDF_features[0]), type(dataset_df["tfidf_features"].tolist()[0]))


        #--------------------------------------------------
        
        relevancy_count = 1
        relevant_comments_list = []
        Comments_str = ""
        
        print("Most Relevant Comments w.r.t Query\n")
        for index in indices:
          comment = dataset_df.iloc[index]["text"]
          print(str(relevancy_count) + " relevant comment: " + comment)
          relevancy_count = relevancy_count + 1
          relevant_comments_list.append(comment)
          Comments_str = Comments_str + comment + ". "
        
        
        with open(Relevant_Comments_List_Pickle_Path, 'wb') as f:
          pickle.dump(relevant_comments_list, f)  

        #---------------------------------------------------------

        relevant_comments_list = []

        with open(Relevant_Comments_List_Pickle_Path, 'rb') as f:
          relevant_comments_list = pickle.load(f)

        #relevant_comments_str = relevant_comments_list[0]
        relevant_comments_str = ". ".join(relevant_comments_list) #merging all comments into a single string.
        #--------------------------------------------

        model_name='SyedShaheer/distilbart-cnn-12-6_TUNED'
        model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

        #----------------------------------------------

        tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

        #-----------------------------------------------

        dialogue = relevant_comments_str
        
        prompt = f"""
        Comment:
        
        {dialogue}
        
        Generate a summary?
        """
        
        #generation_config = GenerationConfig(max_new_tokens=10, do_sample=True, temperature=0.5)
        
        inputs = tokenizer(prompt, return_tensors='pt')
        
        
        output = tokenizer.decode(
            model.generate(
                inputs["input_ids"],
                max_new_tokens=100,
                #generation_config=generation_config,
                )[0],
            skip_special_tokens=True
        )
        
        print("-----\n")
        print(f'INPUT PROMPT:\n{prompt}')
        
        print("-----\n")
        print(f'MODEL GENERATION - \n{output}\n')
        
        # Perform prediction using input_value here
        prediction = input_value  # Dummy prediction, replace with actual prediction
        return render_template('index.html', prediction=output)
    return render_template('index.html', prediction=None)

if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/May/2024 16:05:44] "GET / HTTP/1.1" 200 -

{0.7373680911465129: 626, 0.5495423774232141: 86, 0.5365413154608141: 141, 0.5291798752764473: 901, 0.4159450725060595: 254, 0.40593734363480277: 179, 0.38137554012133507: 632, 0.3741044996276017: 170, 0.3504861444633495: 825, 0.3400878214315499: 126, 0.3391823687092825: 704, 0.33736068481973475: 127, 0.3299536816436222: 88, 0.3152543507023387: 717, 0.3058433248296772: 616, 0.29934602077101535: 677, 0.2913888369334931: 670, 0.2851996390351258: 66, 0.2792948598720801: 726, 0.27877595658055687: 603, 0.27777532161988644: 755, 0.27724572653926915: 751, 0.27157934194755595: 656, 0.26388477435031765: 669, 0.26237730460132974: 662, 0.25692285675798515: 695, 0.2509319413221322: 738, 0.2505902450921788: 694, 0.24761993572808774: 95, 0.24446517399154138: 72, 0.24248737171439477: 770, 0.24245315812022616: 739, 0.24066983673001732: 808, 0.23252363911991009: 753, 0.23218935708231075: 799, 0.23051087426124356: 798, 0.22020306641223972: 659, 0.2166532096603969: 789, 0.21644155621343697: 627, 0.2160875454109009: 108, 0.2129441214213388: 767, 0.21292350927228038: 761, 0.21177043520419733: 747, 0.2105500655075822: 160, 0.20905639837485113: 2, 0.20800016807118943: 719, 0.20530847536790298: 771, 0.20476127397947363: 893, 0.20436206032281598: 861, 0.20402578834905344: 749, 0.20233618821886173: 649, 0.20218001870451452: 318, 0.19779084952492515: 971, 0.19758142969000925: 678, 0.19650779222940729: 841, 0.19569658436543316: 123, 0.1950761296914434: 892, 0.19413718310099184: 736, 0.19050024639880636: 628, 0.19045217486018062: 324, 0.18862450093034988: 609, 0.18746943949832579: 15, 0.18729974985162728: 829, 0.1867777575935182: 759, 0.18494832222898575: 944, 0.18406581654048024: 869, 0.18150602995138884: 828, 0.18026429048761192: 976, 0.1766365890273676: 845, 0.17635527770968598: 985, 0.1761865009994197: 760, 0.17602028897020455: 782, 0.17395853598076808: 1001, 0.1693849239625048: 840, 0.16551345964457823: 606, 0.16491315369328274: 720, 0.16481427743978985: 93, 0.16378852334770844: 661, 0.16153406588978375: 651, 0.15810176483478022: 957, 0.1578221008311148: 226, 0.1570335382418874: 437, 0.15681309933016574: 819, 0.15619227000410735: 703, 0.15393561713801543: 264, 0.15012795519954059: 921, 0.14704411654004143: 777, 0.14656588139864993: 189, 0.14462503488723052: 999, 0.14407069982073303: 439, 0.1417025064253727: 792, 0.14089032788893227: 631, 0.13994096793133656: 115, 0.13958332630157813: 668, 0.13951539318889367: 256, 0.13898769121940766: 876, 0.13737083838168726: 131, 0.13625776160599098: 41, 0.13387817571378027: 52, 0.13361693884113227: 225, 0.12751394256286852: 233, 0.12485538807523727: 610, 0.12477456384325616: 1034, 0.12289095018538067: 252, 0.1196863351199075: 209, 0.11813022278892876: 164, 0.11783929841958665: 805, 0.11751764249993805: 59, 0.1171663628637125: 690, 0.11598044993664719: 842, 0.11501946680938335: 1039, 0.11496496807693707: 193, 0.11426210398714683: 471, 0.11379744500155213: 173, 0.11246932206082165: 878, 0.11060276895468628: 991, 0.10898445197314602: 1006, 0.10782351897987077: 100, 0.10777873155008473: 949, 0.10762787535850901: 260, 0.10704980025848908: 46, 0.10700386480029589: 862, 0.1057688116432226: 165, 0.10564003456032948: 903, 0.1039862909463699: 979, 0.10326523934792388: 721, 0.10308230588759101: 1004, 0.10246979820849135: 740, 0.10060853194692142: 983, 0.09717663836753268: 806, 0.0967670981415941: 619, 0.09652644277677982: 832, 0.09559495769092442: 334, 0.09481511948533308: 222, 0.09455406433388185: 278, 0.0940621519890117: 731, 0.09369755579031636: 724, 0.09286440114302766: 712, 0.09256660789852947: 207, 0.09236450388416906: 793, 0.0904936270147458: 787, 0.0903182905439868: 245, 0.08997008622938187: 905, 0.08993479296517434: 813, 0.08976002227026889: 1042, 0.0895049896325046: 929, 0.08882672984275632: 109, 0.08843403755840995: 24, 0.08841569996063876: 507, 0.08792604466687659: 907, 0.08764102360365449: 596, 0.0872792963889197: 940, 0.08660146170270738: 673, 0.08604874938069888: 27, 0.08572776469792465: 79, 0.08353388581371188: 926, 0.08261477446723983: 388, 0.08256550394736427: 671, 0.0812259082375195: 966, 0.08111949425454304: 50, 0.0809973965087026: 931, 0.08064618755654483: 371, 0.0803631162995831: 918, 0.0791191840906527: 894, 0.07900591187820245: 426, 0.07808111028256041: 45, 0.0780049894580754: 967, 0.07762649885554962: 600, 0.07762636316030186: 916, 0.07749328644607566: 970, 0.07738130147583522: 1041, 0.07692637952533486: 954, 0.07685116589489101: 855, 0.07674518597100004: 1021, 0.07638052679854071: 955, 0.07592509127570354: 167, 0.07588400990352522: 92, 0.07539081223527362: 653, 0.0743470322044537: 546, 0.07396520793007923: 987, 0.07330151099493985: 871, 0.07323860778054475: 1003, 0.07314073404455829: 904, 0.07297577679603304: 1022, 0.07259628360234248: 267, 0.0725823458035169: 839, 0.07250140487375706: 664, 0.07242869667576046: 859, 0.07234850203922695: 769, 0.07207766033388184: 63, 0.07153640441000539: 636, 0.07126021350959866: 140, 0.070948611163049: 643, 0.07015601030892707: 909, 0.06986568583556732: 743, 0.06971654940933203: 686, 0.06959892199849402: 791, 0.06955774605099233: 945, 0.06904761584934765: 682, 0.06886920112088418: 1036, 0.06856824019067252: 729, 0.06843389264202884: 452, 0.06817702454082318: 663, 0.0678627079800163: 968, 0.0674794999237979: 687, 0.0673803215671657: 430, 0.0673759979745415: 147, 0.06693838046441332: 986, 0.0667903291101256: 913, 0.06669914146385705: 539, 0.0661719929957521: 1000, 0.06568766559807854: 953, 0.06568539957248178: 754, 0.06551019444843587: 292, 0.06501264338502379: 891, 0.06478218652639013: 938, 0.06446237403327723: 826, 0.06441378925743674: 870, 0.06396424111009888: 781, 0.06376222877179136: 995, 0.06368609844014282: 766, 0.06317371043743959: 702, 0.06311729882761047: 716, 0.06306615974410756: 646, 0.06297387194798915: 797, 0.06290586851351643: 815, 0.06214619909766027: 809, 0.06200264824284903: 897, 0.06187598971582902: 996, 0.061291769858970786: 128, 0.060979990233058036: 803, 0.06078111301052913: 879, 0.06015280703751582: 956, 0.060053961675484775: 683, 0.05948624615837481: 958, 0.059484475924494275: 47, 0.05937606899720657: 932, 0.05935743218318314: 1020, 0.05909210969586497: 962, 0.058204551663632385: 788, 0.05790383078933771: 864, 0.05787425061244058: 912, 0.057830468338029684: 763, 0.057592033509971684: 838, 0.05734885390782599: 975, 0.057219291239172534: 887, 0.057155441789752535: 959, 0.05673051001971333: 774, 0.056694248585876184: 202, 0.056646383812305356: 733, 0.05652555071668592: 1023, 0.05641925069969317: 752, 0.056140445468135375: 1018, 0.05605876428432157: 190, 0.05589084643689756: 910, 0.055009782572688286: 746, 0.05497461313261621: 867, 0.054473495171101186: 969, 0.05391592672531989: 604, 0.053775336269965855: 351, 0.053669817320509065: 73, 0.05343212239623382: 635, 0.05329201084981787: 184, 0.052943794835288695: 854, 0.052702871160196854: 882, 0.052617176058258185: 418, 0.0524336832580966: 784, 0.0520049177854776: 748, 0.051967186250850714: 308, 0.051897555707013945: 737, 0.051790825841813486: 675, 0.05178961565580901: 947, 0.05161747072592608: 676, 0.05147417321858363: 883, 0.05100568671001358: 856, 0.05092273927258946: 898, 0.05065733517065607: 234, 0.05055153751378466: 11, 0.0503505565177345: 617, 0.05013366072959667: 700, 0.049899909086097954: 288, 0.048963602468071805: 513, 0.04873600679768315: 279, 0.04808712214451499: 660, 0.047908533537256666: 974, 0.04762782586355906: 833, 0.0473995540926411: 735, 0.046811805215304675: 691, 0.04676340046175358: 715, 0.04674431529393834: 963, 0.04656923146183568: 323, 0.04635754197522253: 89, 0.046198161437693244: 567, 0.04572124833287542: 1017, 0.04571630605986335: 952, 0.045465279518774125: 725, 0.04543643313302476: 597, 0.045311779358829136: 978, 0.044901288936957655: 314, 0.044642820301819174: 191, 0.04451412288251012: 889, 0.04444096555457466: 625, 0.04389064159057933: 934, 0.043589419570872034: 810, 0.0435267263811898: 401, 0.043322202794124076: 1033, 0.04324390130738538: 338, 0.04320456171509996: 698, 0.043006928273854016: 923, 0.04273150755586588: 948, 0.04265858388993456: 297, 0.04260885987691677: 612, 0.04260457882952079: 337, 0.04247994041144839: 605, 0.04241303699844427: 1028, 0.04215345313850277: 693, 0.04186425647035766: 930, 0.04161052894925464: 133, 0.04124406117186214: 586, 0.04086886839111144: 386, 0.04067282498703531: 734, 0.04051425513648837: 701, 0.0403525654767665: 881, 0.040286318225637364: 992, 0.040116256246272984: 998, 0.039881396916768744: 485, 0.039864719851022676: 900, 0.039287752281392224: 730, 0.03895351621637007: 899, 0.0389282884987687: 1037, 0.03877335051825892: 920, 0.03818087977557861: 732, 0.0379044930231156: 370, 0.0378943280364914: 741, 0.03753836929655204: 927, 0.03752391506375204: 61, 0.037158881533742937: 8, 0.037141875710018625: 146, 0.03705769659459783: 875, 0.03694395152364651: 1040, 0.036905645735550184: 29, 0.03678439062340062: 387, 0.0365626614673493: 248, 0.03651642571265425: 696, 0.03639440202182894: 1043, 0.03626006413317153: 745, 0.03619557397698196: 772, 0.03608301828366103: 935, 0.03607169664358001: 487, 0.036031424469275444: 911, 0.03565144326803166: 866, 0.035645702076084786: 277, 0.035204504187295094: 630, 0.035185411135079454: 1016, 0.035103461025800885: 836, 0.03504560591035813: 807, 0.03492313270997254: 886, 0.03467458395786965: 939, 0.03453803161509157: 84, 0.03428245509875234: 601, 0.034136895316939336: 831, 0.034059101035910345: 398, 0.03405326046985257: 990, 0.03342326828240555: 344, 0.033417361312769636: 144, 0.033071858761161095: 1014, 0.03280116153107366: 633, 0.03224392681024648: 852, 0.03168646413051357: 402, 0.03141449191890494: 821, 0.031249919389582145: 936, 0.031099336806728366: 775, 0.030793047188984003: 835, 0.030635405023961445: 396, 0.030391508565265807: 915, 0.02988322050743363: 816, 0.02972573572137743: 553, 0.029675871870023605: 532, 0.029151172647992694: 263, 0.028787067266439134: 258, 0.02876479510527192: 847, 0.02832106091017273: 188, 0.028305173959476525: 818, 0.028090691815976673: 435, 0.02790563373864695: 1019, 0.02735626777926017: 873, 0.02698622539080541: 1013, 0.026525319806972075: 988, 0.025987073558961876: 414, 0.025507280988064568: 563, 0.024706861837739246: 1027, 0.02467142290759435: 823, 0.02450793191627153: 800, 0.024110531612680917: 977, 0.02404011749364945: 1011, 0.023857959967544317: 403, 0.023100531666546645: 385, 0.023061060576489222: 742, 0.022222792370551848: 306, 0.022192696867620616: 381, 0.021283866020273927: 951, 0.02066345940326443: 589, 0.020164707894461155: 558, 0.020131109547177884: 514, 0.02007571435596651: 268, 0.01991509437201227: 994, 0.018067840449897406: 689, 0.01588893404375634: 980, 0.015210286616013396: 85, 0.01469729726115298: 76, 0.014078329012511484: 620, 0.014064205145951372: 504, 0.013338972616606328: 333, 0.01262922630291603: 860, 0.0122821793796179: 238, 0.012099465388521602: 232, 0.009392740643236638: 790, 0.009183232781436871: 445, 0.006380766789027457: 652, 0.0: 1038}
<class 'numpy.ndarray'> <class 'list'>
<class 'numpy.float64'> <class 'numpy.ndarray'>
Most Relevant Comments w.r.t Query

1 relevant comment: But I don&#39;t want to lose weight
2 relevant comment: Lose weight and muscles.
3 relevant comment: I didn’t really lose weight this wasn’t true for everyone
4 relevant comment: How to get weight
5 relevant comment: Lol when people go Vegan just to lose weight, 10 pounds in 10 months is nothing, you could lose 10 pounds in 2 months with exercise and healthy eating.
6 relevant comment: You will lose weight if you go vegan? Lol I gained 50 pounds 😂
7 relevant comment: How do you do keto and not lose weight I am already thin trying to get rid of pain.
8 relevant comment: &quot;On the plus side, expect to lose some weight right away&quot; I&#39;m underweight and it&#39;s difficult for me to achieve a healthier HEAVIER weight. But thanks for presuming everyone wants to lose weight.
9 relevant comment: Well keto diet is actually the best diet to lose weight bt there are some pro as well as cons. I had done this diet last year for about 2 months only bt i was able to lose that extra 7 kilos.  After losing my weight i was lyk ok now there&#39;s no need to continue this diet i can go for low calorie diets which I used to follow daily.  Bt the main thing that disturbed me was that after 3 months of switching my diet i gained much more than i lose.  So u need to follow this diet spiritually and doesn&#39;t need to fullstop this all of a sudden else you&#39;ll end up gaining more than u lose.
10 relevant comment: Did not experience any of the so-called negative effects, but didn’t lose weight either.

127.0.0.1 - - [12/May/2024 16:06:41] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        But I don&#39;t want to lose weight. Lose weight and muscles.. I didn’t really lose weight this wasn’t true for everyone. How to get weight. Lol when people go Vegan just to lose weight, 10 pounds in 10 months is nothing, you could lose 10 pounds in 2 months with exercise and healthy eating.. You will lose weight if you go vegan? Lol I gained 50 pounds 😂. How do you do keto and not lose weight I am already thin trying to get rid of pain.. &quot;On the plus side, expect to lose some weight right away&quot; I&#39;m underweight and it&#39;s difficult for me to achieve a healthier HEAVIER weight. But thanks for presuming everyone wants to lose weight.. Well keto diet is actually the best diet to lose weight bt there are some pro as well as cons. I had done this diet last year for about 2 months only bt i was able to lose that extra 7 kilos.  After losing my weight i was lyk ok now there&#39;s no need to continue this diet i can go for low calorie diets which I used to follow daily.  Bt the main thing that disturbed me was that after 3 months of switching my diet i gained much more than i lose.  So u need to follow this diet spiritually and doesn&#39;t need to fullstop this all of a sudden else you&#39;ll end up gaining more than u lose.. Did not experience any of the so-called negative effects, but didn’t lose weight either.

        Generate a summary?

-----

MODEL GENERATION -
 The keto diet is the best diet to lose weight but there are some pros and cons. After 3 months switching to a low calorie diet i gained more than I lost weight. The author experienced negative effects but didn't lose weight either. After losing weight i was lyk ok now there&#39;s no need to continue this diet i can go for low calorie diets which I used to follow daily.